a = 12
b = 4
print("Arithmetic Operators")
print("a =",a)
print("b =",b)
print("a+b =",a+b)
print("a-b =",a-b)
print("a*b =",a*b)
print("a/b =",a/b)
print("a%b =",a%b)
print("a//b =",a//b)
print("a**b =",a**b)
print()
print("Comparison Operators")
print("a =",a)
print("b =",b)
print("a<b =",a<b)
print("a<=b =",a<=b)
print("a>b =",a>b)
print("a>=b =",a>=b)
print("a==b =",a==b)
print("a!=b =",a!=b)
t = True
f = False
print()
print("Logical Operators")
print("t =",t)
print("f =",f)
print("t AND f =",t and f)
print("t OR f =",t or f)
print("t! =",not t)
print()
print("Bitwise Operators")
print("a =",a)
print("b =",b)
print("a&b =",a&b)
print("a|b =",a|b)
print("a^b =",a^b)
print("~a =",~a)
print("a>>2 =",a>>2)
print("b<<2 =",b<<2)